USERNAME = 'root'
PASSWORD = '123456'
HOST = '127.0.0.1'
PORT = 3306
DATABASE = 'db_test'

#  数据库连接 URI
DB_URI = 'mysql+mysqldb://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOST, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True

# 全文搜索
WHOOSHE_MIN_STRING_LEN = 1

# debug
DEBUG_TB_PROFILER_ENABLED = True

# Database debug
SQLALCHEMY_RECORD_QUERIES = True